[Added] Loading of individual country instead of data from all countries
tomayac/local-reverse-geocoder pull request #41
Opened 2021-06-18 13:12 UTC by helloitsm3

Tried to implement loading of single country instead of getting data from all countries and cities. Helps to reduce the time taken when initializing the app

2021-06-18 13:17 UTC, tomayac requested changes
Thanks for the proposal. At the moment it looks like this is hardcoding the country to `SG`, though. If this becomes a feature, it should be configurable at initialization time.

2021-06-18 13:36 UTC, helloitsm3 commented
> Thanks for the proposal. At the moment it looks like this is hardcoding the country to `SG`, though. If this becomes a feature, it should be configurable at initialization time.

I was using "SG" to test out to see if it was able to grab only SG.txt. Users will need to specify the country they plan to grab and it'll dump the data into geonames_dump folder

2021-06-18 13:37 UTC, tomayac commented
Yes, but your PR right now hardcodes this.

2021-06-18 13:51 UTC, helloitsm3 commented
> Yes, but your PR right now hardcodes this.

Sorry, my bad. I'll remove it and make another pull request

2021-06-18 13:56 UTC, tomayac commented
The way this works should be: 

```js
const geocoder = require('local-reverse-geocoder');
geocoder.init(
  {
    load: {
      admin1: true,
      admin2: false,
      admin3And4: false,
      alternateNames: false,
    },
    countries: ['SG'], // <== New, defaults to all countries
  },
  function () {
    // Ready to call lookUp
  }
);
```

2021-06-18 16:22 UTC, helloitsm3 commented
> The way this works should be: 
> 
> 
> 
> ```js
> 
> const geocoder = require('local-reverse-geocoder');
> 
> geocoder.init(
> 
>   {
> 
>     load: {
> 
>       admin1: true,
> 
>       admin2: false,
> 
>       admin3And4: false,
> 
>       alternateNames: false,
> 
>     },
> 
>     countries: ['SG'], // <== New, defaults to all countries
> 
>   },
> 
>   function () {
> 
>     // Ready to call lookUp
> 
>   }
> 
> );
> 
> ```

Okay thanks. I'll make the necessary changes later

2021-06-21 06:36 UTC, tomayac commented on app.js
> +      countries: ['SG', 'AU', 'US'], // <== New, defaults to all countries if array is empty
```suggestion
      countries: [],
```

2021-06-21 06:36 UTC, tomayac commented on app.js
> +      countries: ['SG', 'AU', 'US'], // <== New, defaults to all countries if array is empty
Else, everyone who downloads the library will request your country defaults.

2021-06-21 07:19 UTC, tomayac reviewed
Could you add documentation in the README how people would use this, please?

2021-06-21 07:20 UTC, helloitsm3 commented
> Could you add documentation in the README how people would use this, please?

Yes. I'll work on that and push it later

2021-06-22 10:51 UTC, tomayac approved these changes
LGTM, approval.

Thanks for this. I'll make some minor adjustments and will release a new build soon.

2021-06-22 10:51 UTC, merged

2021-06-22 11:21 UTC, tomayac commented
Fixes https://github.com/tomayac/local-reverse-geocoder/issues/23. 

The release just went out as v0.11.0. Thanks again! You're also credited in the README :-)